[tool.poetry]
name = "webpy"
version = "0.1.0"
description = "webp & webm conversion"
authors = ["Tommi Saltiola <tommi@tommisaltiola.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
